Repository Narantsatsralt05/red-cross-repo, pull requests merged in 2022-05, with the labels that each got.

#146 themFontSize
  src/components/core/fontSizes.jsx
  src/components/core/text.jsx
  src/theme/theme(OLD).jsx
Labels: enhancement

#139 117-admin-page
  src/assets/icon/ring.svg
  src/assets/icon/search.svg
  src/components/common/dashSideBar.jsx
  src/components/common/data-table.jsx
  src/components/common/data.jsx
  src/components/common/index.js
  src/components/common/styled-component.jsx
  src/components/core/border.jsx
  src/components/core/index.js
  src/pages/admin.js
Labels: enhancement

#153 adminChecker
  src/components/common/loading.jsx
  src/pages/adminHome.jsx
  src/pages/checker.jsx
  src/pages/index.js
  src/pages/login.jsx
  src/pages/userHome.jsx
  src/providers/authContext.js
Labels: enhancement

#155 informationSectionAddFontSizes
  src/components/common/index.js
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
Labels: enhancement

#161 installRobotoStyle
  src/components/core/text.jsx
Labels: enhancement

#163 Dropdown bug fix
  src/components/common/dropdown.jsx
  src/components/common/index.js
Labels: bug, fix

#165 updateSections
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
Labels: fix

#158 140 registered users
  src/assets/icon/Shape.svg
  src/assets/icon/excel.svg
  src/assets/icon/line.svg
  src/assets/icon/plus.svg
  src/assets/icon/upline.svg
  src/assets/icon/warning.svg
  src/components/common/index.js
  src/components/common/registered.jsx
  src/components/index.js
  src/theme/color.jsx
Labels: enhancement

#168 adminPageTopInfo
  src/hooks/useDocument.js
  src/pages/admin.js
  src/pages/adminHome.jsx
Labels: enhancement

#170 created-UserIfno2
  src/assets/icon/checkboxIcon.svg
  src/pages/UserInfo2.js
Labels: enhancement

#137 [firebase] rightBar Firebase
  src/components/common/delete.jsx
  src/components/common/dropdown.jsx
  src/components/common/informationSection.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/rightBar.jsx
  src/components/common/rightBarCheck.jsx
  src/components/core/button.jsx
  src/components/core/input.jsx
  src/components/home/userInformation.jsx
  src/hooks/useCollection.js
  src/hooks/useDocument.js
  src/pages/UserInfo.jsx
  src/pages/userHome.jsx
  styles/globals.css
Labels: enhancement

#174 dashboard last added person section and fix data-table.jsx
  src/components/common/data-table.jsx
  src/hooks/useCollection.js
Labels: enhancement

#178 created user info step2
  src/components/common/tabs.jsx
  src/pages/UserInfo2.js
  src/pages/UserInfo2.jsx
Labels: enhancement

#180 114 success page
  src/assets/icon/addIcon.js
  src/assets/icon/correctIcon.js
  src/components/common/header.jsx
  src/components/core/text.jsx
  src/pages/login.jsx
  src/pages/successPage.jsx
Labels: enhancement

#177 [uptade] refactorProjectStructure
  package.json
  src/common/context/AuthContext.jsx
  src/common/context/LoaderContext.jsx
  src/common/services/firebase/firebase.js
  src/common/services/firebase/index.js
  src/components/common/dashSideBar.jsx
  src/components/common/data-table.jsx
  src/components/common/delete.jsx
  src/components/common/dropdown.jsx
  src/components/common/index.jsx
  src/components/common/informationSection.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/loading.jsx
  src/components/common/registered.jsx
  src/components/common/rightBarCheck.jsx
  src/components/common/stepper.jsx
  src/components/core/index.jsx
  src/hooks/authContextTest.jsx
  src/hooks/firebase.js
  src/hooks/index.js
  src/hooks/useCollection.js
  src/hooks/useDocument.js
  src/pages/UserInfo2.jsx
  src/pages/_app.js
  src/pages/admin/home.jsx
  src/pages/admin/index.jsx
  src/pages/index.jsx
  src/pages/test.jsx
  src/pages/user/Info.jsx
  src/pages/user/Info2.jsx
  src/pages/user/checker.jsx
  src/pages/user/forgotPass.jsx
  src/pages/user/home.jsx
  src/pages/user/login.jsx
  src/pages/user/register.jsx
  src/pages/user/signup.jsx
  src/pages/userHome.jsx
  src/providers/authContext.js
  styles/globals.css
  yarn.lock
Labels: enhancement

#181 edit
  src/pages/user/home.jsx
Labels: enhancement

#182 [uptade] pathEdit
  src/pages/user/home.jsx
Labels: enhancement

#150 user home
  src/components/common/data-table.jsx
  src/components/common/informationSections/sections.jsx
  src/components/core/fontSizes.jsx
  src/components/core/stack.jsx
  src/components/core/text.jsx
  src/pages/ProfileHome.js
  src/pages/user/home.jsx
Labels: enhancement

#185 Profile Home Update
  src/components/core/fontSizes.jsx
  src/components/core/shadow.jsx
  src/pages/user/ProfileHome.jsx
  src/pages/user/home.jsx
Labels: enhancement

#187 admin and user pages update and create tooo many update
  src/assets/icon/add.svg
  src/assets/icon/hamburger.svg
  src/assets/icon/textGrammer.svg
  src/components/common/data-table.jsx
  src/components/common/data.jsx
  src/components/common/header.jsx
  src/components/common/index.jsx
  src/components/common/registered.jsx
  src/components/common/styled-component.jsx
  src/components/common/tabs.jsx
  src/components/common/volunteerInformation.jsx
  src/components/core/index.jsx
  src/components/core/stack.jsx
  src/pages/admin/home.jsx
  src/pages/admin/index.jsx
Labels: enhancement

#188 Fontsize update
  src/components/core/text.jsx
Labels: enhancement

#190 [component] userInfo
  src/common/context/LoaderContext.jsx
  src/components/common/delete.jsx
  src/components/common/dropdown.jsx
  src/components/common/informationSection.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/rightBarCheck.jsx
  src/components/common/userInfo.jsx
  src/components/core/input.jsx
  src/components/core/stack.jsx
  src/pages/admin/home.jsx
  src/pages/user/Info.jsx
  src/pages/user/home.jsx
  styles/globals.css
Labels: enhancement

#191 189 registered page update
  src/assets/icon/upline.svg
  src/components/common/header.jsx
  src/components/common/registered.jsx
  src/pages/admin/registeredUsers.jsx
  src/theme/color.jsx
Labels: enhancement

#194 fix pages path 2022.05.20
  src/pages/admin/home.jsx
  src/pages/checker.jsx
  src/pages/login.jsx
Labels: fix

#195 admin and User Info Pages Update and update too many update
  src/common/context/AuthContext.jsx
  src/components/common/data-table.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/registered.jsx
  src/components/common/volunteerInformation.jsx
  src/components/core/text.jsx
  src/pages/admin/index.jsx
Labels: fix

#197 Sign up interface
  package-lock.json
  src/common/context/AuthContext.jsx
  src/components/common/dropdown.jsx
  src/components/common/page-input-task.jsx
  src/hooks/useDocument.js
  src/pages/user/signup.jsx
Labels: enhancement

#198 Profile home update & Hosting
  .eslintrc.json
  .firebase/hosting.b3V0.cache
  .firebaserc
  .gitignore
  firebase.json
  next.config.js
  package-lock.json
  package.json
  src/components/common/dashSideBar.jsx
  src/components/common/header.jsx
  src/components/common/index.jsx
  src/components/common/leftbar.jsx
  src/components/common/registered.jsx
  src/components/common/rightBarCheck.jsx
  src/components/common/styled-component.jsx
  src/components/common/tabs.jsx
  src/components/common/userCard.jsx
  src/components/common/volunteerInformation.jsx
  src/components/core/dashSideBar.jsx
  src/components/core/fontSizes.jsx
  src/components/core/stack.jsx
  src/pages/admin/index.jsx
  src/pages/admin/registeredUsers.jsx
  src/pages/checker.jsx
  src/pages/index.jsx
  src/pages/login.jsx
  src/pages/successPage.jsx
  src/pages/user/Info2.jsx
  src/pages/user/ProfileHome.jsx
  src/pages/user/forgotPass.jsx
  src/pages/user/home.jsx
  src/pages/user/signup.jsx
  yarn.lock
Labels: enhancement

#199 [component] User info
  src/components/common/dropdown.jsx
  src/components/common/index.jsx
  src/components/common/informationSection.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/tabs.jsx
  src/components/common/userInfo.jsx
  src/components/core/text.jsx
  src/pages/index.jsx
  src/pages/test.jsx
  src/pages/user/Info.jsx
  src/pages/user/home.jsx
Labels: enhancement

#200 179 user info step 1 2 holboh
  src/components/common/header.jsx
  src/components/common/stepper.jsx
  src/pages/admin/home.jsx
  src/pages/successPage.jsx
  src/pages/user/Info.jsx
  src/pages/user/Info2.jsx
  src/pages/user/register.jsx
Labels: enhancement

#201 [fix] fix
  src/components/common/informationSection.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/tabs.jsx
  src/components/common/userInfo.jsx
  src/pages/user/Info.jsx
  src/pages/user/ProfileHome.jsx
Labels: enhancement

#204 Login page media query
  src/common/context/AuthContext.jsx
  src/common/services/firebase/firebase.js
  src/pages/checker.jsx
  src/pages/login.jsx
  src/pages/login/UseOnPC.jsx
  src/pages/login/UseOnPhone.jsx
  src/pages/login/UseOnTablet.jsx
Labels: enhancement

#202 196 addwork rightbar
  src/components/common/add-work.jsx
  src/components/common/dropdown.jsx
  src/components/common/index.jsx
  src/pages/admin/home.jsx
Labels: enhancement

#207 [fix] fixHover
  src/components/common/dropdown.jsx
  src/components/common/informationSection.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/tabs.jsx
  src/components/common/userInfo.jsx
  src/components/core/input.jsx
  src/pages/user/Info.jsx
  src/pages/user/ProfileHome.jsx
Labels: enhancement

#208 Signup modal
  src/common/context/AuthContext.jsx
  src/pages/login/UseOnPC.jsx
  src/pages/login/UseOnPhone.jsx
  src/pages/login/UseOnTablet.jsx
Labels: enhancement

#203 fix pages path again and fixing some checkers
  src/common/context/AuthContext.jsx
  src/components/common/data.jsx
  src/components/common/stepper.jsx
  src/components/common/styled-component.jsx
  src/components/common/volunteerInformation.jsx
  src/pages/admin/home.jsx
  src/pages/admin/index.jsx
  src/pages/checker.jsx
  src/pages/index.jsx
  src/pages/login.jsx
  src/pages/login/UseOnPC.jsx
  src/pages/login/UseOnTablet.jsx
  src/pages/register.jsx
  src/pages/successPage.jsx
  src/pages/user/Info.jsx
  src/pages/user/ProfileHome.jsx
  src/pages/user/forgotPass.jsx
Labels: enhancement

#209 [fix] fixPagesBackFront
  package.json
  src/assets/icon/men 1.svg
  src/common/context/AuthContext.jsx
  src/common/services/firebase/firebase.js
  src/components/common/add-work.jsx
  src/components/common/data-table.jsx
  src/components/common/delete.jsx
  src/components/common/dropdown.jsx
  src/components/common/header.jsx
  src/components/common/informationSections/sections.jsx
  src/components/common/informationSections/table.jsx
  src/components/common/page-input-task.jsx
  src/components/common/rightBarCheck.jsx
  src/components/common/stepper.jsx
  src/components/common/tabs.jsx
  src/components/common/userCard.jsx
  src/components/common/userInfo.jsx
  src/components/core/input.jsx
  src/pages/admin/index.jsx
  src/pages/checker.jsx
  src/pages/login/UseOnPC.jsx
  src/pages/login/UseOnPhone.jsx
  src/pages/login/UseOnTablet.jsx
  src/pages/register.jsx
  src/pages/successPage.jsx
  src/pages/user/Info.jsx
  src/pages/user/Info2.jsx
  src/pages/user/ProfileHome.jsx
  src/pages/user/signup.jsx
Labels: enhancement
