Repository Narantsatsralt05/red-cross-repo, pull requests merged in 2022-03, with the labels that each got.

#31 #8 created padding component
  src/styled-component/padding.jsx
Labels: enhancement

#33 InputComponent
  package-lock.json
  package.json
  src/components/input.jsx
  yarn.lock
Labels: enhancement

#32 #15 created margin component
  src/component/stack.jsx
  src/styled-component/center.jsx
  src/styled-component/margin.jsx
  src/styled-component/styled-component.jsx
  src/test.jsx
  src/text.jsx
Labels: enhancement

#23 19-created-position-component
  src/components/position.jsx
  yarn.lock
Labels: enhancement

#45 [web] Login-page
  .babelrc
  .prettierrc.json
  next.config.js
  package-lock.json
  package.json
  src/assest/icon/gishuun.svg
  src/assest/icon/sainDuriin.svg
  src/assest/icon/tuslamj.svg
  src/assest/image/Logo.svg
  src/components/button.jsx
  src/components/index.js
  src/components/input.jsx
  src/components/notificationModal.jsx
  src/components/notificationModalStyle.jsx
  src/components/position.jsx
  src/components/styledBorder.jsx
  src/pages/_app.js
  src/pages/_document.js
  src/pages/index.js
  src/pages/login.jsx
  src/styled-component/Image.jsx
  src/styled-component/center.jsx
  src/styled-component/margin.jsx
  src/styled-component/padding.jsx
  src/styled-component/stack.jsx
  src/styled-component/text.jsx
  src/test.jsx
  src/text.jsx
  styles/globals.css
  yarn.lock
Labels: enhancement

#49 [web] ESlint
  .eslintrc.json
  package.json
  src/components/common/notificationModal.jsx
  src/components/core/button.jsx
  src/components/core/input.jsx
  src/pages/_app.js
  src/pages/_document.js
  src/pages/api/hello.js
  src/pages/index.js
  src/pages/login.jsx
Labels: enhancement

#61 Core component syntax fix
  src/components/core/border.jsx
  src/components/core/button.jsx
  src/components/core/input.jsx
  src/components/core/position.jsx
  src/components/core/text.jsx
Labels: fix

#68 Doc - Update contribution file
  docs/contribution.md
Labels: documentation

#66 56 create login page
  src/assets/icon/gishuun.svg
  src/assets/icon/logo.svg
  src/assets/icon/sainDuriin.svg
  src/assets/icon/tuslamj.svg
  src/assets/image/Logo.svg
  src/components/core/button.jsx
  src/components/core/image.jsx
  src/components/core/input.jsx
  src/components/core/position.jsx
  src/components/core/stack.jsx
  src/components/core/text.jsx
  src/components/index.js
  src/components/index.jsx
  src/pages/home.jsx
  src/pages/index.js
  src/pages/login.jsx
  src/providers/authContext.js
Labels: enhancement

#65 userCard component
  package-lock.json
  package.json
  src/assets/icon/blue.png
  src/assets/icon/blue.svg
  src/assets/icon/female.svg
  src/assets/icon/male.svg
  src/components/common/userCard.jsx
  src/components/core/border.jsx
  src/components/index.js
  yarn.lock
Labels: enhancement
