Repository Narantsatsralt05/red-cross-repo, pull requests merged in 2022-04, with the labels that each got.

#85 Createheader-55
  src/assets/icon/arrow.svg
  src/assets/icon/group.svg
  src/assets/icon/hamburger.svg
  src/assets/icon/help.svg
  src/assets/icon/line.svg
  src/assets/icon/people.svg
  src/assets/icon/profile.svg
  src/assets/icon/saindur.svg
  src/assets/icon/toirog.svg
  src/components/common/header.jsx
  src/components/common/userCard.jsx
  src/pages/index.js
  yarn.lock
Labels: enhancement

#84 76 pagination component test
  src/assets/icon/female.svg
  src/assets/icon/green.svg
  src/assets/icon/grey.svg
  src/components/common/paginationtext.jsx
  src/pages/index.js
Labels: enhancement

#83 Create select component
  package-lock.json
  package.json
  src/assets/icon/arrowDown.svg
  src/components/icons/ArrowDown.jsx
  src/components/select.jsx
  src/pages/_app.js
  src/pages/api/hello.js
  src/pages/index.js
  src/pages/login.jsx
  styles/globals.css
  styles/option.css
  yarn.lock
Labels: enhancement

#93 fix conflicts in multiple files
  src/pages/_app.js
  src/pages/index.js
  src/pages/login.jsx
Labels: bug

#95 fix conflict
  package.json
  styles/globals.css
Labels: bug

#97 [component] validInformation
  src/assets/icon/help.svg
  src/components/common/page-input-task.jsx
  src/components/home/userInformation.jsx
  src/pages/home.jsx
Labels: enhancement

#100 theme-provider
  src/theme/color.jsx
  src/theme/font.jsx
  src/theme/theme(OLD).jsx
  src/theme/theme.jsx
Labels: enhancement

#101 FixSomeBugsToPages
  src/pages/forgotPass.jsx
  src/pages/home.jsx
  src/pages/index.js
  src/pages/login.jsx
  src/providers/authContext.js
Labels: bug

#102 [component] Modal Loading
  package.json
  src/components/common/loading.jsx
  src/components/home/userInformation.jsx
  src/pages/login.jsx
  styles/globals.css
  yarn.lock
Labels: enhancement

#108 Update contribution file
  docs/contribution.md
Labels: documentation

#105 [component] 71 create dash board side bar
  src/assets/icon/addIcon.js
  src/assets/icon/blue.svg
  src/assets/icon/green.svg
  src/assets/icon/grey.svg
  src/components/core/dashSideBar.jsx
Labels: enhancement

#109 86-component-leftbar
  src/assets/icon/help.svg
  src/assets/icon/people.svg
  src/assets/icon/profile.svg
  src/assets/icon/saindur.svg
  src/components/common/leftbar.jsx
  src/components/core/stack.jsx
  src/pages/index.js
Labels: enhancement

#111 Shadow styled component
  src/components/core/shadow.jsx
Labels: enhancement

#116 [component] rightBar using component
  src/assets/icon/ArrowDown.jsx
  src/assets/icon/Group 5 (1).svg
  src/assets/icon/Line 12.svg
  src/assets/icon/image 1.svg
  src/components/common/animation.jsx
  src/components/common/delete.jsx
  src/components/common/informationSection.jsx
  src/components/common/rightBar.jsx
  src/components/common/rightBarCheck.jsx
  src/components/common/select.jsx
  src/components/core/button.jsx
  src/components/core/input.jsx
  src/components/core/position.jsx
  src/pages/home.jsx
  src/pages/test.jsx
  styles/globals.css
Labels: enhancement

#110 Stepper
  src/components/common/stepper.jsx
  src/components/core/text.jsx
  src/components/index.js
Labels: enhancement

#119 input component fix
  src/components/core/input.jsx
  src/pages/home.jsx
  src/theme/theme.jsx
Labels: enhancement, fix

#134 created disable input
  src/components/core/input.jsx
Labels: enhancement

#141 fix-dropdown
  src/assets/icon/arrDown.jsx
  src/components/common/select.jsx
Labels: bug
